services:
  pg-slave:
    image: postgres:17
    container_name: pg_burung_slave
    environment:
      POSTGRES_PASSWORD: slavepass
      POSTGRES_USER: postgres
    ports:
      - "5433:5432"
    volumes:
      - pg_slave_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis_burung_cache
    ports:
      - "6379:6379"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_burung_message_broker
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped

  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: meilisearch_burung_search_engine
    environment:
      MEILI_MASTER_KEY: "SuperSecureKey123456"
    ports:
      - "7700:7700"
    restart: unless-stopped

  cassandra:
    image: cassandra:4.1
    container_name: cassandra_burung_hystorical_data
    environment:
      - CASSANDRA_CLUSTER_NAME=burung_cluster
      - CASSANDRA_NUM_TOKENS=8
    ports:
      - "9042:9042"
    restart: unless-stopped

volumes:
  pg_slave_data:
